version: '3'
services:
  solr:
    image: solr:9.4.0
    container_name: solr
    ports:
      - 8983:8983
    volumes:
      #- ./solr-config:/opt/solr/server/solr/configsets
      - ./solr-data:/var/solr
    environment:
      - SOLR_CORES_DISABLE_CONF_RELOAD=true
        #- SOLR_HOME=/opt/solr/server/solr
        #    command: 
        #- solr-precreate
        #- lnc

